### ISSUE TITLE
error saving results

### ISSUE THREAD

**Issue by Collantes90** [alvarosantamariagomez/sari#11]
**Describe the bug**
If you subtract the plate movement, it does not save the results correctly, it rounds them off and puts signs afterwards.

**To Reproduce**
simply process an IGS station (I just used ALME) and download the data with and without plate movement, you can see it directly in the files.

**Screenshots**
![imagen](https://github.com/user-attachments/assets/ab5108eb-ca33-46f0-85c2-ec50f942c5cc)

![imagen](https://github.com/user-attachments/assets/bf9ae187-0953-4a38-ad04-8b99231327e7)

**Version (please complete the following information):**
directly from the last web link

Depending on how SARI was accessed, provide the following details: 
windows, in all browser

**Comment by alvarosantamariagomez** [comment]
Thanks for the information.  
It turns out this problem only shows up when running SARI on a Linux machine, for instance with the Shinyapps or Docker versions.  
I might need to go into the details of this, but for the time being, I just uploaded a patch on the beta version here:  
https://alvarosg.shinyapps.io/saribeta  

Could you please check if the patch solves your problem?
Note that the beta version is only available temporally and has significantly reduced online ressources, compared to the official stable version.
The next stable version will be released this week.

**Comment by Collantes90** [comment]
Alvaro everything perfect in the beta!!!! 

Gracias!!!!!!!!!

**Comment by alvarosantamariagomez** [comment]
Fixed by 707229aba990918d9c9f608b8dca61f6837cef77 and d42389dc00c6659b162053331de094bc9c2a7a79 included in the [diciembre 2024](https://github.com/alvarosantamariagomez/sari/releases/tag/2024.12) release.
