### ISSUE TITLE
Message error: 'unused argument: type = "cairo-png"''

### ISSUE THREAD

**Issue by egdeory** [alvarosantamariagomez/sari#8]
When running SARI I got the message error 'unused argument: type = "cairo-png"'.

The versions I'm working with:
R version: 4.3.1 (2023-06-16 ucrt)
RStudio version: 2023.6.0.421 

PC specifications:
Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz   2.90 GHz

Is there something I'm doing wrong?

Regards

**Comment by alvarosantamariagomez** [comment]
It may be that your R version was installed without cairo-png support on Windows.  
Since this problem already happened before, it's probably time to abandon cairo-png in SARI.  
Could please install the "ragg" package and then try the latest modification of the app.R code?
It works on my side with no apparent loss of quality in the plots.

**Comment by egdeory** [comment]
Now it works fine, thank you very much
