### ISSUE TITLE
Doubts

### ISSUE THREAD

**Issue by Collantes90** [alvarosantamariagomez/sari#9]
Good morning, 

First of all congratulations again for this work, it is very useful and easy to use.

I have a couple of doubts.

Working from the online platform, I am trying to process data from IGS stations and they only appear up to the letter L. On the other hand, when loading a series from some repository, I can not remove the movement of the plate. Has anything changed since the last update? 

I also wanted to ask if it is possible to download the data once the offsets have been entered, I save them but they keep coming up with them... I must be doing something wrong.

Best regards and thanks for your attention!

Translated with DeepL.com (free version)

**Comment by alvarosantamariagomez** [comment]
The dropdown menu uses the [selectize.js](https://github.com/selectize/selectize.js/) control, which by default, only shows the first 1000 station IDs, most likely to keep the UI responsive.  
You can type any character and the dropdown menu will automatically filter the station IDs having that character. Type two characters and the station you are looking for should appear in the proposed list.  
However, you need to know the station ID you're looking for, and I realize that users may not know exactly the station ID they are looking for. So I could add a link to show the full list of available stations on a new browser tab.

Concerning the plate motion, if you cannot plot the predicted linear trend, nor remove it, most probably means that the station coordinates are missing. Could you please tell me which repository are you using? For IGS series this should not be a problem.

Concerning the offsets, you can download the _original_ series, the fitted model and the _residual_ series, but you cannot download the series without the offsets only, because the estimated offsets depend to some extent on the other fitted parameters.  
Anyway, if you still want to get the _original_ series without the offsets, you can take the _residual_ series from SARI and add the trend value to them.

Thank you for your feedback!

**Comment by Collantes90** [comment]
Thank you very much Alvaro! All clarified, with the movement of the plate was as you said. I have put the coordinates by hand and it seems to work, although it is true that in the observation file were already. They are own stations are not servers.

Greetings!

**Comment by alvarosantamariagomez** [comment]
Glad all is sorted out.
The problem with most of the NEU/ENU series is that any information in the header is format-free and SARI will not read it.
However, there are a few exceptions to this.
If your series were downloaded from a server known to SARI, and they have something in the header that allows them to be identified, a new exception could be added.
